### ISSUE TITLE
Enhancement: Use Data annotations for customizing output.

### ISSUE THREAD

**Issue by pykong** [tdwright/contabs#60] opened 2018-11-11 13:50 UTC
Using `contabs` I find myself forced mapping some POCO to some smaller object which only contains a subset of the properties - those I want to show in console.

It would be so much DRYer if I could just use the original POCO.
Thus I would require some way to specify which properties to print and which not.

A common library face with a similiar issue uses data annotation:
https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm

Here an object can be declared "OptIn" and only those properties with such an "OptIn" annotation will actually be serialized. 

Transferred to `contabs` such may look like:

```cs
[ConTabsObject(MemberInclusion.OptIn)]
public class MyPoco {

    [ConTabsProperty] // will be included
    public string PrintMe { get; set; }

     // not opted-in:  will not show up in table
    public string HideMe { get; set; }

    ...

}
```

Of course the such annotations could be used for other purposes as well, like string formatting or column alignment - essentially every option the[ current configuration](https://github.com/tdwright/contabs/wiki/3.-Working-with-columns) offers

**Comment by tdwright** [comment] 2018-11-17 22:42
Hi @pykong,

Great idea. I tend to use the `.Hide` property of a column to achieve this, or LINQ's `.Select()` to create an anonymous type, but this is a nice alternative.

As you say, we could use attributes to set all of the config options we currently set in code. As I'm thinking about it, using methods and properties on a `Table` object is probably better suited to "one-off" code, but annotating the model itself is a better long-term solution and fits more nicely with the principle of separating concerns.

As with all these things, I'd be happy to see a PR, but will otherwise get round to it ASAP.

Cheers,
Tom

**Comment by tdwright** [comment] 2018-11-21 10:50
OK, looking at this now.

I think it will be simpler to go for an annotation which opts-_out_, if that's OK? In my experience, we want most properties to become visible columns. Adding a class (table) level attribute that switches this could be an extension in the future, if it's going to be helpful. For now, though, focusing on purely column-level attributes is an easier way to approach this.

Quick checklist of initial attributes:

- [x] Hiding columns
- [x] Naming columns
- [x] Re-ordering columns

**Comment by tdwright** [comment] 2018-11-21 11:55
Additional attributes for columns:

- [ ] Alignment
- [ ] Long string behaviour (might be tricky)
- [x] Format string

And some table-level ideas
- [ ] Switch table to "opt-in" with regards to column visibility
- [ ] Table styling (also potentially tricky)

I still think I'll leave the table-level options for a potential second pass.

The one's I've marked as potentially more complex are those where we currently set a property to complex type. Might be awkward to express properly in an attribute, but I'll see how I get on.

**Comment by tdwright** [comment] 2018-11-24 10:52
Right then. I've added four column-level attributes:

- `[ConTabsColumnHide()]`
- `[ConTabsColumnName("string")]`
- `[ConTabsColumnPosition(int)]`
- `[ConTabsColumnFormatString("string")]`

I've created [an example `Planet` POCO](https://github.com/tdwright/contabs/blob/5dbf8dc5b1b10a4b42d02e3f6952ff95d97645ac/ConTabsDemo-Attributes/Data.cs#L24-L39) that uses these annotations.

These attributes will get released with the rest of the V2 stuff.

As an aside, it turns out that doing attributes for alignment, long string behaviour, and table styles _will_ be problematic. This is because we define these are complex types that [we can't just pass in to an attribute constructor](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30045).

In order to get these to work, we'd need to add an enum with values pointing to predetermined values. The problem with this (that I'd been trying to avoid by designing them in the way they have been) is that this kills extensibility. At the very least we'd be creating a two-tier system, where "official" methods get a shortcut, but custom ones don't. Perhaps this isn't a problem, and the pragmatic solution may be to cater to the majority of users, who don't specify custom ways of handling these things.

Anyway, I'm waffling. I think unless and until someone asks for these things, I'm going to avoid rushing into making a decision. For now, I think these four attributes allow us to dip our toes in the water and see how we like it.

Happy for me to close this?

**Comment by pykong** [comment] 2018-11-24 15:11
@tdwright I am pleased you took bite at this.
I am going to test drive the new data annotations tomorrow.

Regarding the question of "OptIn" vs "OptOut":
I believe we should start with the most simple implementation. This could mean starting with only a single opt behavior.
Still, I believe having both the possibility to opt for either is a very convenient and should be considered in future release.

With the new features being added, I believe `contabs` now positions itself to be the prime console table package for .NET.

**Comment by pykong** [comment] 2018-11-25 21:00
Looks good to me.

**Comment by tdwright** [comment] 2018-12-19 08:32
@pykong Looks like v2.0 won't be ready for a little while longer yet, so I've put out a preview that contains this functionality. https://www.nuget.org/packages/ConTabs.tdwright/2.0.0-preview1

Going to close this issue now.

Merry Christmas! 🎅 🎁

**Closed as completed by tdwright** 2018-12-19 08:32 UTC
Labels: enhancement

**Comment by pykong** [comment] 2018-12-19 15:36
Merry Christmas, thanks for the gift Santa Wright!
